name: Check for New Videos

on:
  # Runs on a schedule (every 15 minutes)
  schedule:
    - cron: '*/15 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to check for new videos
        # Pass secrets as environment variables to the Python script
        env:
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commit and push updated last video link
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_video_link.txt
          # Commit only if there are changes
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update last video link"
            git push
          fi